/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/audit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_audit']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['callback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Start the login. Dev mode signs the dev user in directly. */
    get: operations['login']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/connections': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_connections']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/connections/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['start_connection']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/connections/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Remove a connection. The grant is revoked at Google first so the account's
     *     permissions page stops listing this app, but a failure there does not keep
     *     the row: the person asked for it to be gone.
     */
    delete: operations['delete_connection']
    options?: never
    head?: never
    patch: operations['patch_connection']
    trace?: never
  }
  '/api/connections/{id}/reconnect': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['reconnect_connection']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/google/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Where Google sends the browser back. Everything that can go wrong here ends
     *     as `/connections?error=<code>`, because the person is looking at a page and
     *     not at a JSON envelope; the process log carries the detail.
     */
    get: operations['google_callback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * The person's own clock, for the portal and for every tool. The name is
     *     checked here rather than at the column: a zone the tz database does not
     *     know would render every time in the wrong place, and the message names a
     *     few that work so nobody has to guess the spelling.
     */
    patch: operations['patch_me']
    trace?: never
  }
  '/api/scopes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['scopes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tokens': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list_tokens']
    put?: never
    post: operations['create_token']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/tokens/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['revoke_token']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/dl/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Spend one use of a link and stream the bytes. Unauthenticated by design:
     *     knowing the id is the permission.
     */
    get: operations['download']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description One row of the log, as the activity page reads it. */
    AuditDto: {
      args?: unknown
      /** Format: date-time */
      at: string
      /** Format: int64 */
      connection_id?: number | null
      detail?: string | null
      /** Format: int64 */
      duration_ms?: number | null
      /** Format: int64 */
      id: number
      ip?: string | null
      kind: string
      outcome: string
      /** Format: int64 */
      token_id?: number | null
      tool?: string | null
      /** Format: int64 */
      user_id?: number | null
    }
    /** @description A page of the log and where the next one continues. */
    AuditPage: {
      entries: components['schemas']['AuditDto'][]
      /** @description The `before` value that continues this page, or null at the end. */
      next?: string | null
    }
    /** @description `POST /api/connections/start`: a label and the services to ask Google for. */
    ConnectInput: {
      label: string
      /**
       * @description Registry service names; `drive` is added when `docs` or `sheets` is
       *     ticked, because both read through Drive.
       */
      services: string[]
    }
    ConnectionDto: {
      /** Format: date-time */
      created_at: string
      delegate_ok: boolean
      google_email: string
      /**
       * @description What Google actually granted, which the consent screen lets a person
       *     narrow.
       */
      granted_scopes: string[]
      /** Format: int64 */
      id: number
      label: string
      /** Format: date-time */
      last_used_at?: string | null
      /**
       * @description True when the grant is narrower than the ticked services need: the UI
       *     shows such a connection as partial and offers a reconnect.
       */
      partial: boolean
      services: string[]
      /** @description "ok", "needs_reauth" or "revoked" */
      status: string
      status_detail?: string | null
    }
    /**
     * @description `PATCH /api/connections/{id}`. Everything else about a connection comes
     *     from Google.
     */
    ConnectionPatchInput: {
      /** @description Whether a delegate token may reach this connection. */
      delegate_ok?: boolean | null
      label?: string | null
    }
    /** @description Where the browser is sent to consent. */
    ConsentUrl: {
      url: string
    }
    ErrorBody: {
      error: components['schemas']['ErrorDetail']
    }
    ErrorDetail: {
      code: string
      message: string
    }
    /**
     * @description What a monitor and the container's HEALTHCHECK ask for. The database is the
     *     only thing whose absence makes the server useless, so it alone decides the
     *     status; the other two are reported so a deployment can see why connecting
     *     an account or reading a PDF does not work.
     */
    Health: {
      database: boolean
      /** @description `GMCP_GOOGLE_CLIENT_ID` and `GMCP_GOOGLE_CLIENT_SECRET` are set */
      google: boolean
      /** @description poppler's `pdftotext`, without which PDF text extraction is refused */
      pdftotext: boolean
      /** @description "ok" or "error" */
      status: string
    }
    Me: {
      /** @description How many connections this principal can reach */
      connections: number
      /**
       * @description False when `GMCP_GOOGLE_CLIENT_ID` and `GMCP_GOOGLE_CLIENT_SECRET` are
       *     unset: the connections page says so instead of offering Connect.
       */
      google_configured: boolean
      /** @description "session", "token" or "delegate" */
      kind: string
      scopes: string[]
      /** @description How many tokens this person manages */
      tokens: number
      user: components['schemas']['UserDto']
    }
    /**
     * @description What a person may change about themselves. One field so far, and the
     *     portal sends only what it is changing.
     */
    MePatch: {
      /** @description An IANA zone name, e.g. "Europe/Warsaw" */
      timezone: string
    }
    /**
     * @description `POST /api/connections/{id}/reconnect`: the same account, optionally with a
     *     different set of services.
     */
    ReconnectInput: {
      services?: string[] | null
    }
    ScopeDto: {
      /** @description The level on its own, e.g. `write`; null for `delegate`. */
      level?: string | null
      /** @description The scope this one is useless without, which the UI ticks along. */
      requires?: string | null
      /** @description The string a token stores, e.g. `docs:write`. */
      scope: string
      /** @description The MCP tools this scope unlocks. */
      tools: string[]
    }
    /** @description `/api/scopes`: the registry the token grid is drawn from. */
    ScopeRegistry: {
      /** @description The client profiles a token may carry. */
      clients: string[]
      /** @description The one non-matrix scope. */
      delegate: components['schemas']['ScopeDto']
      services: components['schemas']['ServiceDto'][]
    }
    ServiceDto: {
      /** @description What connecting this service asks Google for. */
      google_scopes: string[]
      levels: components['schemas']['ScopeDto'][]
      service: string
    }
    /** @description The one time the secret is ever shown. */
    TokenCreated: components['schemas']['TokenDto'] & {
      /** @description Store it now; the server keeps only its hash. */
      secret: string
    }
    TokenDto: {
      all_connections: boolean
      /** @description "generic", "openwebui", "claude-code" or "opencode" */
      client: string
      /** @description The allowlist, when there is one. */
      connection_ids: number[]
      /** Format: date-time */
      created_at: string
      delegate: boolean
      /** Format: int64 */
      id: number
      /** Format: date-time */
      last_used_at?: string | null
      name: string
      /** Format: date-time */
      revoked_at?: string | null
      scopes: string[]
      /**
       * Format: int64
       * @description The person the token acts as; null for a delegate token.
       */
      user_id?: number | null
    }
    /** @description `POST /api/tokens`. */
    TokenInput: {
      /** @description Every current and future connection of the person. Personal tokens only. */
      all_connections?: boolean
      /** @description The client profile; "generic" when absent. */
      client?: string | null
      /** @description The allowlist, when `all_connections` is not set. Personal tokens only. */
      connection_ids?: number[]
      name: string
      /** @description `service:level` strings, plus `delegate` for a gateway token. */
      scopes: string[]
    }
    UserDto: {
      /** Format: date-time */
      created_at: string
      email?: string | null
      /** Format: int64 */
      id: number
      /** Format: date-time */
      last_login_at?: string | null
      name?: string | null
      /**
       * @description The IANA zone this person's times are shown in, in the portal and in
       *     every MCP tool.
       */
      timezone: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_audit: {
    parameters: {
      query?: {
        /** @description Not before this instant, RFC 3339. */
        from?: string | null
        /** @description Not after this instant, RFC 3339. */
        to?: string | null
        connection?: number | null
        token?: number | null
        /** @description One of the audit kinds, e.g. `tool_call` or `link_used`. */
        kind?: string | null
        /** @description An MCP tool name. */
        tool?: string | null
        limit?: number | null
        /** @description The `next` of the previous page: `<instant>,<id>`. */
        before?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuditPage']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  callback: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      303: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description not a member of the required group, when one is configured */
      403: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description redirect to the identity provider */
      303: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_connections: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConnectionDto'][]
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  start_connection: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConnectInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConsentUrl']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  delete_connection: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  patch_connection: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConnectionPatchInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConnectionDto']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  reconnect_connection: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReconnectInput']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConsentUrl']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  google_callback: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description back to /connections, with ?connected=<id> or ?error=<code> */
      303: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Me']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  patch_me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MePatch']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Me']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  scopes: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ScopeRegistry']
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  list_tokens: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenDto'][]
        }
      }
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_token: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenInput']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenCreated']
        }
      }
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  revoke_token: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  download: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description the link id */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description the file, as an attachment */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description unknown, expired or spent */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
}
